Repository wzc520pyfm/ant-design-x-vue, pull requests merged in 2025-05, with the labels that each got.

#285 feat(bubble): footer support function
  docs/component/bubble.md
  docs/examples-setup/bubble/header-and-footer.vue
  docs/examples/bubble/header-and-footer.vue
  src/bubble/Bubble.vue
  src/bubble/interface.ts
Labels: Bubble, 1.2

#270 fix(theme): fix theme system
  src/theme/useToken.ts
Labels: 1.2

#272 build: improve build conf and dist
  .gitignore
  package.json
  pnpm-lock.yaml
  tsconfig.build.json
  vite.config.mts
  vite.config.umd.mts
Labels: 1.2

#241 fix(thought-chain): fix controlled mode not working
  docs/component/thought-chain.md
  docs/examples-setup/thought-chain/controlled.vue
  docs/examples/thought-chain/controlled.vue
  src/thought-chain/hooks/useCollapsible.ts
Labels: ThoughtChain
